# Site settings
title:       Venture Unknown
email:       joe@ventureunknown.com
author:      Venture Unknown
description: "Infrastructure and scaling resources for startups."
baseurl:     ""
url:         "http://www.ventureunknown.com"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     10
sass:
  compressed: true
